name: tests

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run the tests suite manually from the Actions tab
  workflow_dispatch:

  # Allows you to run the tests suite before building release artifacts
  workflow_call:

jobs:

  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install the project
        run: uv sync --group dev

  lint:
    runs-on: ubuntu-latest
    needs:
      - setup
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: chartboost/ruff-action@v1

  typecheck:
    runs-on: ubuntu-latest
    needs:
      - setup
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Check types
        run: |
          uv run mypy src/plaster_yaml/

  unittests:
    runs-on: ubuntu-latest
    needs:
      - setup
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Run tests
        run: |
          uv run pytest tests --junitxml=junit/test-results-${{ matrix.python-version }}.xml --cov=celery_yaml --cov-report=xml --cov-report=html

      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml

      - name: Codecov
        if: matrix.python-version == '3.12' && github.event_name != 'workflow_dispatch'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
